import Vue from 'vue'
import 'element-ui/lib/theme-chalk/index.css'
// 导入弹框提示组件
import {
    Button,
    Form,
    FormItem,
    Input,
    Message,
    Container,
    Header,
    Aside,
    Main,
    Menu,
    MenuItem,
    MenuItemGroup,
    Submenu,
    RadioGroup,
    RadioButton,
    Breadcrumb,
    BreadcrumbItem,
    Card,
    Row,
    Col,
    Table,
    TableColumn,
    Switch,
    Tooltip,
    Pagination,
    Dialog,
    Select,
    Option,
    Divider,
    DatePicker,
    Tag,
    Popover,
    Popconfirm,
    Empty,
    Autocomplete,
    CheckboxGroup,
    Checkbox,
    Alert,
    Notification,
    Backtop,
    InputNumber,
    ButtonGroup,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Drawer,
    Link,
    Tabs,
    TabPane,
    Result,
    Loading,
    Collapse,
    CollapseItem,
    Step,
    Steps,
    Descriptions,
    DescriptionsItem,
    Progress,
    TimePicker,
    TimeSelect
} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(RadioGroup)
Vue.use(RadioButton)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Select)
Vue.use(Option)
Vue.use(Divider)
Vue.use(DatePicker)
Vue.use(Tag)
Vue.use(Popover)
Vue.use(Popconfirm)
Vue.use(Empty)
Vue.use(Autocomplete)
Vue.use(CheckboxGroup)
Vue.use(Checkbox)
Vue.use(Alert)
Vue.use(Backtop)
Vue.use(InputNumber)
Vue.use(ButtonGroup)
Vue.use(DropdownMenu)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(Drawer)
Vue.use(Link)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Loading)
Vue.use(Result)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Descriptions)
Vue.use(DescriptionsItem)
Vue.use(Progress)
Vue.use(TimePicker)
Vue.use(TimeSelect)
Vue.prototype.$message = Message
Vue.prototype.$notify = Notification
